# Generated by Django 5.2 on 2026-02-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100)),
                (
                    "telephone",
                    models.CharField(
                        help_text="Format: +223... ou +225...", max_length=20
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_related",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Généré automatiquement (ex: ML-2402-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "type_transport",
                    models.CharField(
                        choices=[("AERIEN", "Aérien"), ("MARITIME", "Maritime")],
                        default="AERIEN",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("FERME", "Fermé"),
                            ("EXPEDIE", "Expédié"),
                            ("ARRIVE", "Arrivé au Pays"),
                            ("DOUANE", "En Douane"),
                            ("DISPONIBLE", "Disponible pour retrait"),
                        ],
                        default="OUVERT",
                        max_length=20,
                    ),
                ),
                (
                    "frais_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût du transport Chine -> Pays",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "frais_douane",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Frais de dédouanement à l'arrivée",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_expedition", models.DateTimeField(blank=True, null=True)),
                ("date_arrivee", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_related",
                        to="core.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Colis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Poids en kg",
                        max_digits=10,
                    ),
                ),
                (
                    "cbm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Volume en m3 (Maritime)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "prix_transport",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût transport calculé",
                        max_digits=12,
                    ),
                ),
                (
                    "prix_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix total à payer par client",
                        max_digits=12,
                    ),
                ),
                ("est_paye", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="colis/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECU", "Reçu Chine"),
                            ("EXPEDIE", "Expédié"),
                            ("ARRIVE", "Arrivé Pays"),
                            ("LIVRE", "Livré Client"),
                        ],
                        default="RECU",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="colis",
                        to="core.client",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_related",
                        to="core.country",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis",
                        to="core.lot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["country"], name="core_client_country_96857d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(fields=["country"], name="core_lot_country_20dd4b_idx"),
        ),
        migrations.AddIndex(
            model_name="colis",
            index=models.Index(
                fields=["country"], name="core_colis_country_9d13fd_idx"
            ),
        ),
    ]
