# Generated by Django 5.2 on 2026-02-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_client_lot_colis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
    ]
