# Generated by Django 5.2 on 2026-02-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots_destination",
                to="core.country",
            ),
        ),
    ]
