# Generated by Django 5.2 on 2026-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lot_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Généré automatiquement (ex: CARGO-2402-001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="type_transport",
            field=models.CharField(
                choices=[
                    ("CARGO", "Cargo"),
                    ("EXPRESS", "Express"),
                    ("BATEAU", "Bateau"),
                ],
                default="CARGO",
                max_length=20,
            ),
        ),
    ]
