# Generated by Django 5.2 on 2026-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_lot_numero_alter_lot_type_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Observations (modifiable même après expédition)",
                null=True,
            ),
        ),
    ]
