# Generated by Django 5.2 on 2026-02-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_lot_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="hauteur",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Hauteur (cm)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="largeur",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Largeur (cm)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="longueur",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Longueur (cm)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="type_colis",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("TELEPHONE", "Téléphone"),
                    ("ELECTRONIQUE", "Électronique"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colis",
            name="cbm",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Volume en m3 (Calculé auto: L*l*h/1000000)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="colis",
            name="poids",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Poids (kg) - utilisé pour Cargo/Express",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_transport",
                    models.CharField(
                        choices=[
                            ("CARGO", "Cargo"),
                            ("EXPRESS", "Express"),
                            ("BATEAU", "Bateau"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prix_kilo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix par Kg (pour Cargo/Express)",
                        max_digits=10,
                    ),
                ),
                (
                    "prix_cbm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix par m3 (pour Bateau)",
                        max_digits=10,
                    ),
                ),
                (
                    "surcharge_telephone",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix fixe par téléphone",
                        max_digits=10,
                    ),
                ),
                (
                    "surcharge_electronique",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Surcharge par unité électronique",
                        max_digits=10,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_related",
                        to="core.country",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        help_text="Pays de destination",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifs",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "destination", "type_transport"),
                        name="unique_tarif_per_dest_transport",
                    )
                ],
            },
        ),
    ]
