# Generated by Django 5.2 on 2026-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_colis_hauteur_colis_largeur_colis_longueur_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarif",
            name="surcharge_electronique",
        ),
        migrations.RemoveField(
            model_name="tarif",
            name="surcharge_telephone",
        ),
        migrations.AddField(
            model_name="colis",
            name="nombre_pieces",
            field=models.IntegerField(
                default=1, help_text="Nombre de pièces (requis pour Téléphone)"
            ),
        ),
        migrations.AddField(
            model_name="tarif",
            name="prix_piece",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix par pièce (Téléphone)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="prix_cbm",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix par m3 (Bateau)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="prix_kilo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix par Kg (Cargo/Express)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="type_transport",
            field=models.CharField(
                choices=[
                    ("CARGO", "Cargo"),
                    ("EXPRESS", "Express"),
                    ("BATEAU", "Bateau"),
                    ("TELEPHONE", "Téléphone (Prix par pièce)"),
                ],
                max_length=20,
            ),
        ),
    ]
