# Generated by Django 5.2 on 2026-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_tarif_surcharge_electronique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo globale du lot",
                null=True,
                upload_to="lots/%Y/%m/",
            ),
        ),
    ]
