# Generated by Django 5.2 on 2026-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_lot_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colis",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
