# Generated by Django 5.2 on 2026-02-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_backgroundtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="commentaire_livraison",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="colis",
            name="infos_recepteur",
            field=models.CharField(
                blank=True,
                help_text="Nom/Tel de la personne qui récupère (si différent du client)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="mode_livraison",
            field=models.CharField(
                choices=[
                    ("AGENCE", "Retrait Agence"),
                    ("DOMICILE", "Livraison Domicile"),
                ],
                default="AGENCE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="montant_jc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant Jeton Cédé (Remise/Ecart caisse)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="whatsapp_notified",
            field=models.BooleanField(
                default=False, help_text="Notification WhatsApp envoyée/demandée"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("OUVERT", "Ouvert"),
                    ("FERME", "Fermé"),
                    ("EN_TRANSIT", "En Transit"),
                    ("EXPEDIE", "Expédié"),
                    ("ARRIVE", "Arrivé au Pays"),
                    ("DOUANE", "En Douane"),
                    ("DISPONIBLE", "Disponible pour retrait"),
                ],
                default="OUVERT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("GLOBAL_ADMIN", "Global Admin"),
                    ("ADMIN_CHINE", "Admin Chine"),
                    ("AGENT_CHINE", "Agent Chine"),
                    ("AGENT_MALI", "Agent Mali"),
                    ("AGENT_RCI", "Agent RCI"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=20,
            ),
        ),
    ]
