# Generated by Django 5.2 on 2026-02-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_colis_commentaire_livraison_colis_infos_recepteur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
