# Generated by Django 5.2 on 2026-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_colis_updated_at_lot_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remuneration_mode",
            field=models.CharField(
                choices=[("SALAIRE", "Salaire Fixe"), ("COMMISSION", "Commission (%)")],
                default="SALAIRE",
                help_text="Type de rémunération de l'agent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="remuneration_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant du salaire ou Pourcentage de commission",
                max_digits=12,
            ),
        ),
    ]
