# Generated by Django 5.2 on 2026-02-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_client_user"),
        ("core", "0014_user_remuneration_mode_user_remuneration_value"),
    ]

    operations = []
