# Generated by Django 5.2 on 2026-02-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_merge_20260218_0333"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="notifie_fermeture",
            field=models.BooleanField(
                default=False,
                help_text="Notification 'lot fermé' déjà envoyée pour ce colis",
            ),
        ),
    ]
