# Generated by Django 5.2 on 2026-03-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_notifie_fermeture_to_colis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colis",
            name="poids",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Poids (kg) - utilisé pour Cargo/Express",
                max_digits=10,
                null=True,
            ),
        ),
    ]
