# Generated by Django 5.2 on 2026-03-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_imageproxytoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageProxyToken",
        ),
    ]
