# Generated by Django 5.2 on 2026-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_delete_imageproxytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="prix_kilo_manuel",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix au kilo défini manuellement par l'agent (pour TypeColis=Manuel)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="sortie_autorisee_par",
            field=models.CharField(
                blank=True,
                help_text="Nom du supérieur ou collègue ayant autorisé la sortie",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="sortie_sous_garantie",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le colis a été sorti avec l'autorisation d'un garant",
            ),
        ),
        migrations.AlterField(
            model_name="colis",
            name="type_colis",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("TELEPHONE", "Téléphone"),
                    ("ELECTRONIQUE", "Électronique"),
                    ("MANUEL", "Manuel"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
    ]
