# Generated by Django 5.2 on 2026-03-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_colis_prix_kilo_manuel_colis_sortie_autorisee_par_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colis",
            name="hauteur",
        ),
        migrations.RemoveField(
            model_name="colis",
            name="largeur",
        ),
        migrations.RemoveField(
            model_name="colis",
            name="longueur",
        ),
        migrations.AlterField(
            model_name="colis",
            name="cbm",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Volume en m3 (Saisie manuelle pour Bateau)",
                max_digits=10,
            ),
        ),
    ]
