# Generated by Django 5.2 on 2026-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_colis_hauteur_remove_colis_largeur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="paye_en_chine",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le colis a été encaissé par l'agence en Chine",
            ),
        ),
    ]
