# Generated by Django 5.2 on 2026-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_colis_paye_en_chine"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESPECE", "Espèce"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("SARALI", "Sarali"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colis",
            name="reste_a_payer",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant restant à payer par le client",
                max_digits=12,
            ),
        ),
    ]
