# Generated by Django 5.2 on 2026-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_colis_mode_paiement_colis_reste_a_payer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colis",
            options={"verbose_name": "Carton", "verbose_name_plural": "Cartons"},
        ),
        migrations.RemoveIndex(
            model_name="colis",
            name="core_colis_country_9d13fd_idx",
        ),
        migrations.AddField(
            model_name="lot",
            name="nb_colis",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de colis groupés dans ce lot (ex: 33 colis pour 415 cartons)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("GLOBAL_ADMIN", "Global Admin"),
                    ("ADMIN_CHINE", "Admin Chine"),
                    ("AGENT_CHINE", "Agent Chine"),
                    ("ADMIN_MALI", "Admin Mali"),
                    ("AGENT_MALI", "Agent Mali"),
                    ("AGENT_RCI", "Agent RCI"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=20,
            ),
        ),
    ]
