# Generated by Django 5.2 on 2026-03-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_colis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="date_encaissement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="colis",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
    ]
