# Generated by Django 5.2 on 2026-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_avancesalaire"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="colis",
                    name="ajoute_par_mali",
                    field=models.BooleanField(
                        default=False,
                        help_text="Colis ajouté directement par l'admin Mali dans un lot arrivé",
                    ),
                ),
                migrations.AddField(
                    model_name="colis",
                    name="date_encaissement",
                    field=models.DateField(
                        blank=True,
                        help_text="Date à laquelle le paiement a été encaissé",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="colis",
                    name="date_livraison",
                    field=models.DateField(
                        blank=True,
                        help_text="Date à laquelle le colis a été livré au client",
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                # Uniquement le champ qui n'existe pas encore en prod
                migrations.AddField(
                    model_name="colis",
                    name="ajoute_par_mali",
                    field=models.BooleanField(
                        default=False,
                        help_text="Colis ajouté directement par l'admin Mali dans un lot arrivé",
                    ),
                ),
                migrations.AddField(
                    model_name="colis",
                    name="date_encaissement",
                    field=models.DateField(
                        blank=True,
                        help_text="Date à laquelle le paiement a été encaissé",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="colis",
                    name="date_livraison",
                    field=models.DateField(
                        blank=True,
                        help_text="Date à laquelle le colis a été livré au client",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
