# Generated by Django 5.2 on 2026-03-25 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_mali_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientLotTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_kilo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix au kilo négocié",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_mali",
                    models.ForeignKey(
                        help_text="Admin ayant validé le tarif",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs_speciaux",
                        to="core.client",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs_speciaux",
                        to="core.lot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif Spécial Client/Lot",
                "verbose_name_plural": "Tarifs Spéciaux Client/Lot",
                "unique_together": {("client", "lot")},
            },
        ),
    ]
