# Generated by Django 5.2 on 2026-03-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_clientlottarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientlottarif",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_speciaux_recus",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="clientlottarif",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_speciaux",
                to="core.lot",
            ),
        ),
    ]
