# Generated by Django 5.2 on 2026-03-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_clientlottarif_destination_alter_clientlottarif_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientlottarif",
            name="type_transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARGO", "Cargo"),
                    ("EXPRESS", "Express"),
                    ("BATEAU", "Bateau"),
                ],
                help_text="S'applique uniquement à ce type de transport (Cargo/Express)",
                max_length=20,
                null=True,
            ),
        ),
    ]
