# Generated by Django 5.2 on 2026-03-27 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_clientlottarif_type_transport"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncaissementColis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant encaissé lors de cette transaction",
                        max_digits=12,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("ESPECE", "Espèce"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("SARALI", "Sarali"),
                            ("AUTRE", "Autre"),
                        ],
                        default="ESPECE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "colis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaissements",
                        to="core.colis",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaissements_colis_realises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaissement Colis",
                "verbose_name_plural": "Encaissements Colis",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
