# Generated by Django 5.2 on 2026-03-29 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_encaissementcolis"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="solde_avoir",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Crédit disponible pour payer des colis",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="encaissementcolis",
            name="methode",
            field=models.CharField(
                choices=[
                    ("ESPECE", "Espèce"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("SARALI", "Sarali"),
                    ("AVOIR", "Avoir Client"),
                    ("AUTRE", "Autre"),
                ],
                default="ESPECE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AvoirMouvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOT", "Dépôt / Recharge"),
                            ("CONSOMMATION", "Consommation (Paiement Colis)"),
                            ("CORRECTION", "Correction / Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_recu",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de reçu ou référence transaction",
                        max_length=50,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements_avoir",
                        to="core.client",
                    ),
                ),
                (
                    "colis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_avoir",
                        to="core.colis",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement Avoir",
                "verbose_name_plural": "Mouvements Avoir",
                "ordering": ["-created_at"],
            },
        ),
    ]
