# Generated by Django 5.2 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_client_solde_avoir_alter_encaissementcolis_methode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="paye_par_avance",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le colis a été payé par imputation d'avoir (Avance)",
            ),
        ),
        migrations.AlterField(
            model_name="colis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESPECE", "Espèce"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("SARALI", "Sarali"),
                    ("AVANCE", "Avance"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="encaissementcolis",
            name="methode",
            field=models.CharField(
                choices=[
                    ("ESPECE", "Espèce"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("SARALI", "Sarali"),
                    ("AVANCE", "Avance / Avoir"),
                    ("AUTRE", "Autre"),
                ],
                default="ESPECE",
                max_length=20,
            ),
        ),
    ]
