# Generated by Django 5.2 on 2026-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_colis_paye_par_avance_alter_colis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ESPECE', 'Espèce'), ('ORANGE_MONEY', 'Orange Money'), ('SARALI', 'Sarali'), ('WAVE', 'Wave'), ('AVANCE', 'Avance')], max_length=20, null=True),
        ),
    ]
