# Generated by Django 5.2 on 2026-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_colis_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissementcolis',
            name='methode',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('ORANGE_MONEY', 'Orange Money'), ('SARALI', 'Sarali'), ('WAVE', 'Wave'), ('AVANCE', 'Avance / Avoir'), ('AUTRE', 'Autre')], default='ESPECE', max_length=20),
        ),
    ]
