# Generated by Django 5.2 on 2026-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_personnesortie"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_aerien_access",
            field=models.BooleanField(
                default=True,
                help_text="Indique si l'utilisateur a accès à l'espace Aérien (Cargo/Express)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_maritime_access",
            field=models.BooleanField(
                default=True,
                help_text="Indique si l'utilisateur a accès à l'espace Maritime (Bateau)",
            ),
        ),
    ]
