# Generated by Django 5.2 on 2026-07-29 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_user_has_aerien_access_user_has_maritime_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldeInitialCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_pivot", models.DateField(default=django.utils.timezone.now)),
                (
                    "montant_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "type_transport",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("AERIEN", "Aérien"),
                            ("BATEAU", "Maritime"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Reprise de solde certifiée après décompte physique",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_initiaux",
                        to="core.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde Initial Caisse (Date Pivot)",
                "verbose_name_plural": "Soldes Initiaux Caisse (Dates Pivot)",
                "ordering": ["-date_pivot", "-created_at"],
            },
        ),
    ]
