# Generated by Django 5.2 on 2026-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_soldeinitialcaisse"),
    ]

    operations = [
        migrations.AddField(
            model_name="colis",
            name="is_regularise",
            field=models.BooleanField(
                default=False,
                help_text="Colis sorti du stock (perte/introuvable) sans encaissement",
            ),
        ),
    ]
