# Generated by Django 5.2 on 2026-02-18 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0014_client_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wachap_chine_access_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Token WaChap Chine"
                    ),
                ),
                (
                    "wachap_chine_instance_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Instance ID Chine"
                    ),
                ),
                (
                    "wachap_mali_access_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Token WaChap Mali"
                    ),
                ),
                (
                    "wachap_mali_instance_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Instance ID Mali"
                    ),
                ),
                (
                    "wachap_system_access_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Token WaChap Système"
                    ),
                ),
                (
                    "wachap_system_instance_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Instance ID Système"
                    ),
                ),
                (
                    "rappels_actifs",
                    models.BooleanField(
                        default=False, verbose_name="Activer les rappels automatiques"
                    ),
                ),
                (
                    "delai_rappel_jours",
                    models.IntegerField(
                        default=3,
                        help_text="Nombre de jours après l'arrivée du colis avant d'envoyer un rappel",
                        verbose_name="Délai avant rappel (jours)",
                    ),
                ),
                (
                    "template_rappel",
                    models.TextField(
                        default="Bonjour, votre colis {numero_suivi} est disponible à notre agence depuis {jours} jours. Merci de passer le récupérer.",
                        verbose_name="Message de rappel",
                    ),
                ),
                (
                    "developer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Format international (+223...)",
                        max_length=20,
                        verbose_name="Téléphone Développeur (Alertes)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration des Notifications",
                "verbose_name_plural": "Configuration des Notifications",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone_destinataire", models.CharField(blank=True, max_length=20)),
                ("email_destinataire", models.EmailField(blank=True, max_length=254)),
                (
                    "type_notification",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("colis_recu", "Colis Reçu (Chine)"),
                            ("lot_expedie", "Lot Expédié"),
                            ("lot_arrive", "Lot Arrivé (Mali)"),
                            ("colis_livre", "Colis Livré"),
                            ("rappel_colis", "Rappel Colis"),
                            ("otp", "Code OTP"),
                            ("alerte_admin", "Alerte Admin"),
                            ("alerte_dev", "Alerte Développeur"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("envoye", "Envoyé"),
                            ("echec", "Échec"),
                            ("echec_permanent", "Échec Permanent"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "message_id_externe",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID WaChap/Email"
                    ),
                ),
                ("erreur_envoi", models.TextField(blank=True)),
                ("nombre_tentatives", models.IntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                ("prochaine_tentative", models.DateTimeField(blank=True, null=True)),
                (
                    "colis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.colis",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["statut"], name="notificatio_statut_8fb4dc_idx"
                    ),
                    models.Index(
                        fields=["categorie"], name="notificatio_categor_2afb0d_idx"
                    ),
                    models.Index(
                        fields=["date_creation"], name="notificatio_date_cr_379b1f_idx"
                    ),
                ],
            },
        ),
    ]
