# Generated by Django 5.2 on 2026-02-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="security_code",
            field=models.CharField(
                default="0000",
                help_text="Code pour afficher/modifier les identifiants sensibles",
                max_length=50,
                verbose_name="Code de sécurité (PIN)",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="template_rappel_groupe",
            field=models.TextField(
                default="Bonjour {client_nom}, vous avez {nombre_colis} colis disponibles à l'agence depuis plus de {jours} jours.\nRéférences : {liste_ref}\nTotal à payer : {total_montant}\nMerci de passer les récupérer.",
                help_text="Variables : {client_nom}, {nombre_colis}, {jours}, {liste_ref}, {total_montant}",
                verbose_name="Message de rappel (Groupé)",
            ),
        ),
        migrations.AlterField(
            model_name="configurationnotification",
            name="template_rappel",
            field=models.TextField(
                default="Bonjour, votre colis {numero_suivi} est disponible à notre agence depuis {jours} jours. Reste à payer : {montant}. Merci de passer le récupérer.",
                verbose_name="Message de rappel (Individuel)",
            ),
        ),
    ]
