# Generated by Django 5.2 on 2026-02-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_configurationnotification_security_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationnotification",
            name="template_rappel_groupe",
        ),
        migrations.AlterField(
            model_name="configurationnotification",
            name="template_rappel",
            field=models.TextField(
                default="Bonjour {client_nom}, vous avez {nombre_colis} colis disponibles à l'agence depuis plus de {jours} jours.\nRéférences : {liste_ref}\nTotal à payer : {total_montant}\nMerci de passer les récupérer.",
                help_text="Variables : {client_nom}, {nombre_colis}, {jours}, {liste_ref}, {total_montant}, {numero_suivi}, {montant}",
                verbose_name="Message de rappel (Adaptatif)",
            ),
        ),
    ]
