# Generated by Django 5.2 on 2026-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0003_remove_configurationnotification_template_rappel_groupe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="test_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Si rempli, TOUTES les notifications seront envoyées à ce numéro (utile pour le local).",
                max_length=20,
                verbose_name="Téléphone de Test (Override)",
            ),
        ),
    ]
