# Generated by Django 5.2 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_configurationnotification_test_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="admin_mali_phone",
            field=models.CharField(
                blank=True,
                help_text="Si rempli, reçoit le rapport journalier WhatsApp à 23h50 (Cargo, Express, Bateau, Dépenses, Solde)",
                max_length=20,
                verbose_name="Téléphone Admin Mali (Rapports journaliers)",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_cote_divoire_access_token",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Token WaChap Côte d'Ivoire"
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_cote_divoire_instance_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Instance ID Côte d'Ivoire"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("colis_recu", "Colis Reçu (Chine)"),
                    ("lot_expedie", "Lot Expédié"),
                    ("lot_arrive", "Lot Arrivé"),
                    ("colis_livre", "Colis Livré"),
                    ("rappel_colis", "Rappel Colis"),
                    ("rapport_journalier", "Rapport Journalier Mali"),
                    ("otp", "Code OTP"),
                    ("alerte_admin", "Alerte Admin"),
                    ("alerte_dev", "Alerte Développeur"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=50,
            ),
        ),
    ]
