# Generated by Django 5.2 on 2026-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_add_cote_divoire_and_admin_mali_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_chine_access_token",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_chine_instance_id",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_cote_divoire_access_token",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_cote_divoire_instance_id",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_mali_access_token",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_mali_instance_id",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_system_access_token",
        ),
        migrations.RemoveField(
            model_name="configurationnotification",
            name="wachap_system_instance_id",
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_account_chine",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account ID Chine (V4)"
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_account_cote_divoire",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account ID Côte d'Ivoire (V4)"
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_account_mali",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account ID Mali (V4)"
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_account_system",
            field=models.CharField(
                blank=True,
                help_text="Utilisé pour les OTP et alertes administrateur",
                max_length=255,
                verbose_name="Account ID Système (V4)",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="wachap_v4_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Clé Bearer commune à tous les comptes WaChap V4",
                max_length=255,
                verbose_name="Clé Secrète WaChap V4 (globale)",
            ),
        ),
    ]
