# Generated by Django 5.2 on 2026-02-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_migrate_to_wachap_v4"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="developer_email",
            field=models.EmailField(
                blank=True,
                help_text="Reçoit toutes les alertes critiques par email (erreurs, déconnexions WaChap, etc.)",
                max_length=254,
                verbose_name="Email Développeur (Alertes système)",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                default="smtp.hostinger.com",
                help_text="Ex: smtp.hostinger.com",
                max_length=255,
                verbose_name="Serveur SMTP",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="smtp_password",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mot de passe SMTP"
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="smtp_port",
            field=models.PositiveIntegerField(
                default=465,
                help_text="465 (SSL) ou 587 (TLS) — Hostinger recommande 465",
                verbose_name="Port SMTP",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="smtp_use_ssl",
            field=models.BooleanField(
                default=True,
                help_text="True pour port 465 (SSL). False avec TLS pour port 587.",
                verbose_name="Utiliser SSL",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="smtp_user",
            field=models.CharField(
                blank=True,
                help_text="Ex: noreply@ts-aircargo.com",
                max_length=255,
                verbose_name="Utilisateur SMTP (Email expéditeur)",
            ),
        ),
    ]
