# Generated by Django 5.2 on 2026-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_add_email_smtp_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="app_version",
            field=models.CharField(
                default="V2.0.1",
                help_text="Numéro de version affiché sur les badges (ex: V2.0.1)",
                max_length=20,
                verbose_name="Version de l'application (Badge)",
            ),
        ),
        migrations.AlterField(
            model_name="configurationnotification",
            name="template_rappel",
            field=models.TextField(
                default="Bonjour *{client_nom}*,\n\n⏰ *Rappel — Colis en attente de retrait*\n\n{'Votre colis' if nombre_colis == 1 else 'Vos {nombre_colis} colis'} {'est disponible' if nombre_colis == 1 else 'sont disponibles'} à l'agence depuis plus de *{jours} jours* :\n{liste_ref}\n\n💰 *Montant à régler : {total_montant}*\n\nMerci de passer les récupérer dès que possible.\n\n🌐 Suivez vos colis : https://ts-aircargo.com/login\n——\n*Équipe TS AIR CARGO* 🇨🇳 🇲🇱 🇨🇮",
                help_text="Variables disponibles : {client_nom}, {nombre_colis}, {jours}, {liste_ref}, {total_montant}, {numero_suivi}, {montant}",
                verbose_name="Message de rappel (Adaptatif)",
            ),
        ),
    ]
