# Generated by Django 5.2 on 2026-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0008_configurationnotification_app_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="admin_mali_phone_2",
            field=models.CharField(
                blank=True,
                help_text="Numéro supplémentaire pour la réception du rapport journalier WhatsApp",
                max_length=20,
                verbose_name="Téléphone Admin Mali 2 (Rapports journaliers)",
            ),
        ),
        migrations.AddField(
            model_name="configurationnotification",
            name="admin_mali_phone_3",
            field=models.CharField(
                blank=True,
                help_text="Numéro supplémentaire pour la réception du rapport journalier WhatsApp",
                max_length=20,
                verbose_name="Téléphone Admin Mali 3 (Rapports journaliers)",
            ),
        ),
    ]
