# Generated by Django 5.2 on 2026-03-13 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_colis_hauteur_remove_colis_largeur_and_more"),
        ("notification", "0009_configurationnotification_admin_mali_phone_2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="region",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Région WaChap"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["region"], name="notificatio_region_4ea381_idx"),
        ),
    ]
