# Generated by Django 5.2 on 2026-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0010_notification_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="activer_rappel_maintenance",
            field=models.BooleanField(
                default=False,
                help_text="Envoie un rappel automatique tous les 5 du mois à l'Admin Mali.",
                verbose_name="Activer le rappel du contrat de maintenance",
            ),
        ),
    ]
