# Generated by Django 5.2 on 2026-05-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0011_configurationnotification_activer_rappel_maintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurationnotification",
            name="activer_rappel_maintenance",
            field=models.BooleanField(
                default=False,
                help_text="Envoie un rappel automatique tous les 6 du mois à l'Admin Mali.",
                verbose_name="Activer le rappel du contrat de maintenance",
            ),
        ),
    ]
