# Generated by Django 5.2 on 2026-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0012_alter_configurationnotification_activer_rappel_maintenance",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationnotification",
            name="template_rappel_groupe",
            field=models.TextField(
                default="Bonjour *{client_nom}*,\n\n⏰ *Rappel — Colis en attente de retrait*\n\nVos *{nombre_colis} colis* sont disponibles à l'agence depuis plus de *{jours} jours* :\n{liste_ref}\n\n💰 *Montant total à régler : {total_montant}*\n\nMerci de passer les récupérer dès que possible.\n\n🌐 Suivez vos colis : https://ts-aircargo.com/login\n——\n*Équipe TS AIR CARGO* 🇨🇳 🇲🇱 🇨🇮",
                help_text="Template pour rappels groupés (plusieurs colis)",
                verbose_name="Message de rappel (Mode Groupé)",
            ),
        ),
    ]
