# Generated by Django 5.2 on 2026-02-15 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0013_colis_updated_at_lot_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=255)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, help_text="Montant en FCFA", max_digits=10
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("LOYER", "Loyer"),
                            ("ELECTRICITE", "Électricité"),
                            ("EAU", "Eau"),
                            ("SALAIRE", "Salaire"),
                            ("TRANSPORT", "Transport"),
                            ("NOURRITURE", "Nourriture"),
                            ("COMMUNICATION", "Communication (Internet/Tel)"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                (
                    "piece_jointe",
                    models.ImageField(
                        blank=True, null=True, upload_to="depenses/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depenses_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depenses",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
