# Generated by Django 5.2 on 2026-02-15 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_colis_updated_at_lot_updated_at"),
        ("report", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransfertArgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Montant transféré en FCFA",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Note ou observation"),
                ),
                (
                    "preuve_image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo du reçu/bordereau",
                        null=True,
                        upload_to="transferts/%Y/%m/",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("RECU", "Reçu"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_initis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pays_expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_sortants",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert d'argent",
                "verbose_name_plural": "Transferts d'argent",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
