# Generated by Django 5.2 on 2026-03-03 04:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_transfertargent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Montant payé en FCFA",
                        max_digits=10,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "periode_mois",
                    models.IntegerField(
                        help_text="Mois de référence (ex: 3 pour Mars)"
                    ),
                ),
                (
                    "periode_annee",
                    models.IntegerField(help_text="Année de référence (ex: 2026)"),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("VIREMENT", "Virement Bancaire"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("AUTRE", "Autre"),
                        ],
                        default="ESPECES",
                        max_length=50,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Référence de transfert, observation, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Agent",
                "verbose_name_plural": "Paiements Agents",
                "ordering": ["-date_paiement", "-created_at"],
            },
        ),
    ]
