# Generated by Django 5.2 on 2026-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_paiementagent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("LOYER", "Loyer"),
                    ("ELECTRICITE", "Électricité"),
                    ("EAU", "Eau"),
                    ("SALAIRE", "Salaire"),
                    ("MATERIELS", "Matériels (Imprimante, Scotch, etc.)"),
                    ("TRANSPORT", "Transport"),
                    ("NOURRITURE", "Nourriture"),
                    ("COMMUNICATION", "Communication (Internet/Tel)"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=50,
            ),
        ),
    ]
