# Generated by Django 5.2 on 2026-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_alter_depense_categorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="is_china_indicative",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, ne sera pas pris en compte dans le solde de caisse Mali",
                verbose_name="Dépense Chine (Indicatif)",
            ),
        ),
        migrations.AddField(
            model_name="transfertargent",
            name="destinataire",
            field=models.CharField(
                choices=[("CHINE", "Chine"), ("GAOUSSOU", "Gaoussou")],
                default="CHINE",
                max_length=20,
            ),
        ),
    ]
