# Generated by Django 5.2 on 2026-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_depense_is_china_indicative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertargent',
            name='destinataire',
            field=models.CharField(choices=[('CHINE', 'Chine'), ('GAOUSSOU', 'Gaoussou'), ('GUISSE', 'Guissé')], default='CHINE', max_length=20),
        ),
    ]
