# Generated by Django 5.2 on 2026-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_alter_transfertargent_destinataire"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="type_transport",
            field=models.CharField(
                blank=True,
                choices=[("AVION", "Avion (Cargo/Express)"), ("BATEAU", "Bateau")],
                help_text="Lier cette dépense à un flux spécifique (laisser vide si global)",
                max_length=20,
                null=True,
            ),
        ),
    ]
