# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_mali_app', '0001_initial'),
        ('agent_chine_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_configuration', models.CharField(help_text='Nom de la configuration', max_length=100, unique=True)),
                ('sms_active', models.BooleanField(default=True)),
                ('orange_sms_api_key', models.CharField(blank=True, help_text='Clé API Orange SMS', max_length=200)),
                ('orange_sms_api_url', models.URLField(blank=True, help_text="URL de l'API Orange SMS")),
                ('orange_sms_sender_id', models.CharField(blank=True, help_text="ID de l'expéditeur pour Orange SMS", max_length=50)),
                ('whatsapp_active', models.BooleanField(default=True)),
                ('twilio_account_sid', models.CharField(blank=True, help_text='SID du compte Twilio', max_length=200)),
                ('twilio_auth_token', models.CharField(blank=True, help_text="Token d'authentification Twilio", max_length=200)),
                ('twilio_whatsapp_number', models.CharField(blank=True, help_text='Numéro WhatsApp Business Twilio', max_length=20)),
                ('email_active', models.BooleanField(default=True)),
                ('email_smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200)),
                ('email_smtp_port', models.IntegerField(default=587)),
                ('email_smtp_user', models.CharField(blank=True, max_length=200)),
                ('email_smtp_password', models.CharField(blank=True, max_length=200)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('max_tentatives_envoi', models.IntegerField(default=3, help_text="Nombre maximum de tentatives d'envoi")),
                ('delai_entre_tentatives', models.IntegerField(default=30, help_text='Délai en minutes entre les tentatives')),
                ('template_colis_cree', models.TextField(default='Votre colis {numero_suivi} a été enregistré dans notre système et sera bientôt expédié. Merci de faire confiance à TS Air Cargo.', help_text='Template pour la création de colis')),
                ('template_lot_expedie', models.TextField(default='Votre colis {numero_suivi} a été expédié dans le lot {numero_lot}. Suivez son statut sur notre plateforme TS Air Cargo.', help_text="Template pour l'expédition de lot")),
                ('template_colis_arrive', models.TextField(default='Bonne nouvelle ! Votre colis {numero_suivi} est arrivé au Mali. Nous vous contacterons pour la livraison.', help_text="Template pour l'arrivée de colis")),
                ('template_colis_livre', models.TextField(default="Votre colis {numero_suivi} a été livré avec succès. Merci d'avoir choisi TS Air Cargo.", help_text='Template pour la livraison de colis')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Notification',
                'verbose_name_plural': 'Configurations Notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-App'), ('email', 'Email')], help_text='Type de notification', max_length=20)),
                ('categorie', models.CharField(choices=[('colis_cree', 'Colis créé'), ('lot_expedie', 'Lot expédié'), ('colis_arrive', 'Colis arrivé'), ('colis_livre', 'Colis livré'), ('transfert_argent', "Transfert d'argent"), ('rapport_operationnel', 'Rapport opérationnel'), ('alerte_systeme', 'Alerte système'), ('information_generale', 'Information générale')], help_text='Catégorie de la notification', max_length=30)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu du message')),
                ('lien_action', models.URLField(blank=True, help_text='Lien vers une action (optionnel)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec'), ('lu', 'Lu')], default='en_attente', max_length=20)),
                ('telephone_destinataire', models.CharField(blank=True, help_text='Numéro de téléphone pour SMS/WhatsApp', max_length=20)),
                ('email_destinataire', models.EmailField(blank=True, help_text='Email pour les notifications email', max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message_id_externe', models.CharField(blank=True, help_text='ID du message du service externe (Twilio, Orange SMS, etc.)', max_length=100)),
                ('erreur_envoi', models.TextField(blank=True, help_text="Détails de l'erreur en cas d'échec d'envoi")),
                ('nombre_tentatives', models.IntegerField(default=0, help_text="Nombre de tentatives d'envoi")),
                ('prochaine_tentative', models.DateTimeField(blank=True, help_text="Date de la prochaine tentative d'envoi", null=True)),
                ('priorite', models.IntegerField(default=1, help_text='Priorité de la notification (1=haute, 5=basse)')),
                ('colis_reference', models.ForeignKey(blank=True, help_text='Référence au colis (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_chine_app.colis')),
                ('destinataire', models.ForeignKey(help_text='Utilisateur destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, help_text='Utilisateur qui a envoyé la notification (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
                ('lot_reference', models.ForeignKey(blank=True, help_text='Référence au lot (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_chine_app.lot')),
                ('transfert_reference', models.ForeignKey(blank=True, help_text="Référence au transfert d'argent (si applicable)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_mali_app.transfertargent')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='notificatio_destina_6cb2f0_idx'), models.Index(fields=['type_notification', 'statut'], name='notificatio_type_no_96b5e9_idx'), models.Index(fields=['date_creation'], name='notificatio_date_cr_3dd4fe_idx')],
            },
        ),
    ]
