# Generated by Django 5.2.4 on 2025-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('colis_cree', 'Colis créé'), ('lot_expedie', 'Lot expédié'), ('colis_en_transit', 'Colis en transit'), ('colis_arrive', 'Colis arrivé'), ('colis_livre', 'Colis livré'), ('transfert_argent', "Transfert d'argent"), ('transfert_recu', 'Transfert reçu'), ('reception_lot', 'Réception de lot'), ('rapport_operationnel', 'Rapport opérationnel'), ('alerte_systeme', 'Alerte système'), ('information_generale', 'Information générale')], help_text='Catégorie de la notification', max_length=30),
        ),
    ]
