# Generated by Django 5.2.4 on 2025-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notification_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_chine_access_token',
            field=models.CharField(blank=True, help_text="Token d'accès WaChap pour l'instance Chine", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_chine_active',
            field=models.BooleanField(default=True, help_text="Activer l'instance WaChap Chine"),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_chine_instance_id',
            field=models.CharField(blank=True, help_text="ID d'instance WaChap Chine", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_chine_webhook_url',
            field=models.URLField(blank=True, help_text="URL webhook pour l'instance Chine (optionnel)"),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_mali_access_token',
            field=models.CharField(blank=True, help_text="Token d'accès WaChap pour l'instance Mali", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_mali_active',
            field=models.BooleanField(default=True, help_text="Activer l'instance WaChap Mali"),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_mali_instance_id',
            field=models.CharField(blank=True, help_text="ID d'instance WaChap Mali", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationnotification',
            name='wachap_mali_webhook_url',
            field=models.URLField(blank=True, help_text="URL webhook pour l'instance Mali (optionnel)"),
        ),
    ]
