# Generated by Django 5.2.4 on 2025-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0005_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec'), ('echec_permanent', 'Échec permanent'), ('annulee', 'Annulée'), ('lu', 'Lu')], default='en_attente', max_length=20),
        ),
    ]
